import { Click, Status, Game, CellMap, Board, Cell, GameMove } from "./types";

const B = Cell.Blank;
const M = Cell.Mine;
type GameMoveTest = {
	move: GameMove;
	game: Game;
	expected: Game;
};

export function dummyGame({
	flagged,
	opened,
	status,
	mines,
}: {
	flagged: `${number}-${number}`[];
	opened: `${number}-${number}`[];
	status: Status;
	mines: number;
}): Game {
	const flaggedMap: CellMap = {};
	const openedMap: CellMap = {};
	flagged.forEach((fc) => {
		flaggedMap[fc] = true;
	});
	opened.forEach((oc) => {
		openedMap[oc] = true;
	});
	return {
		flaggedMap,
		openedMap,
		status,
		minesCount: mines,
	};
}

export const simpleGameBoard: Board = [
	[B, 1, 1],
	[B, 2, M],
	[B, 2, M],
];

export const lostGameTests: GameMoveTest[] = [
	{
		move: { row: 0, col: 1, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: [],
			status: Status.Ready,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-1"],
			status: Status.Started,
			mines: 2,
		}),
	},
	{
		move: { row: 1, col: 2, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: ["0-1"],
			status: Status.Started,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-1", "1-2", "2-2"],
			status: Status.Lose,
			mines: 2,
		}),
	},
	{
		move: { row: 0, col: 0, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: ["0-1", "1-2", "2-2"],
			status: Status.Lose,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-1", "1-2", "2-2"],
			status: Status.Lose,
			mines: 2,
		}),
	},
	{
		move: { row: 0, col: 0, click: Click.Right },
		game: dummyGame({
			flagged: [],
			opened: ["0-1", "1-2", "2-2"],
			status: Status.Lose,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-1", "1-2", "2-2"],
			status: Status.Lose,
			mines: 2,
		}),
	},
];

export const wonGameTests: GameMoveTest[] = [
	{
		move: { row: 0, col: 0, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: [],
			status: Status.Ready,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-0", "0-1", "1-0", "1-1", "2-0", "2-1"],
			status: Status.Started,
			mines: 2,
		}),
	},
	{
		move: { row: 0, col: 2, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: ["0-0", "0-1", "1-0", "1-1", "2-0", "2-1"],
			status: Status.Started,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: ["1-2", "2-2"],
			opened: ["0-0", "0-1", "1-0", "1-1", "2-0", "2-1", "0-2"],
			status: Status.Win,
			mines: 2,
		}),
	},
];

export const flagGameTests: GameMoveTest[] = [
	{
		move: { row: 0, col: 0, click: Click.Right },
		game: dummyGame({
			flagged: [],
			opened: [],
			status: Status.Ready,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: ["0-0"],
			opened: [],
			status: Status.Started,
			mines: 2,
		}),
	},
	{
		move: { row: 0, col: 0, click: Click.Left },
		game: dummyGame({
			flagged: ["0-0"],
			opened: [],
			status: Status.Started,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: ["0-0"],
			opened: [],
			status: Status.Started,
			mines: 2,
		}),
	},
	{
		move: { row: 0, col: 0, click: Click.Right },
		game: dummyGame({
			flagged: ["0-0"],
			opened: [],
			status: Status.Started,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: [],
			opened: [],
			status: Status.Started,
			mines: 2,
		}),
	},
	{
		move: { row: 0, col: 1, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: [],
			status: Status.Started,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-1"],
			status: Status.Started,
			mines: 2,
		}),
	},
	{
		move: { row: 0, col: 1, click: Click.Right },
		game: dummyGame({
			flagged: [],
			opened: ["0-1"],
			status: Status.Started,
			mines: 2,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-1"],
			status: Status.Started,
			mines: 2,
		}),
	},
];

export const completeGameplayBoard: Board = [
	[B, B, 1, 1, 1],
	[1, 2, 4, M, 2],
	[1, M, M, M, 2],
	[2, 3, 3, 2, 1],
	[M, 1, B, B, B],
];
export const completeGameplayTests: GameMoveTest[] = [
	{
		move: { row: 0, col: 1, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: [],
			status: Status.Ready,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-0", "0-1", "0-2", "1-0", "1-1", "1-2"],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 2, col: 4, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: ["0-0", "0-1", "0-2", "1-0", "1-1", "1-2"],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: [],
			opened: ["0-0", "0-1", "0-2", "1-0", "1-1", "1-2", "2-4"],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 4, col: 4, click: Click.Left },
		game: dummyGame({
			flagged: [],
			opened: ["0-0", "0-1", "0-2", "1-0", "1-1", "1-2", "2-4"],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: [],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
			],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 2, col: 3, click: Click.Right },
		game: dummyGame({
			flagged: [],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
			],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: ["2-3"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
			],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 2, col: 0, click: Click.Left },
		game: dummyGame({
			flagged: ["2-3"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
			],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: ["2-3"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
			],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 3, col: 0, click: Click.Left },
		game: dummyGame({
			flagged: ["2-3"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
			],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: ["2-3"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
			],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 4, col: 0, click: Click.Right },
		game: dummyGame({
			flagged: ["2-3"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
			],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: ["2-3", "4-0"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
			],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 0, col: 4, click: Click.Left },
		game: dummyGame({
			flagged: ["2-3", "4-0"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
			],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: ["2-3", "4-0"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
				"0-4",
			],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 1, col: 4, click: Click.Left },
		game: dummyGame({
			flagged: ["2-3", "4-0"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
				"0-4",
			],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: ["2-3", "4-0"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
				"0-4",
				"1-4",
			],
			status: Status.Started,
			mines: 5,
		}),
	},
	{
		move: { row: 0, col: 3, click: Click.Left },
		game: dummyGame({
			flagged: ["2-3", "4-0"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
				"0-4",
				"1-4",
			],
			status: Status.Started,
			mines: 5,
		}),
		expected: dummyGame({
			flagged: ["2-3", "4-0", "1-3", "2-1", "2-2"],
			opened: [
				"0-0",
				"0-1",
				"0-2",
				"1-0",
				"1-1",
				"1-2",
				"2-4",
				"3-1",
				"3-2",
				"3-3",
				"3-4",
				"4-1",
				"4-2",
				"4-3",
				"4-4",
				"2-0",
				"3-0",
				"0-4",
				"1-4",
				"0-3",
			],
			status: Status.Win,
			mines: 5,
		}),
	},
];
